### PR TITLE
Lang select

### PR DESCRIPTION
**Pull request by bdon**
@wipfli we can expose the language list in the JS library so I don't need to copy it here

### CODE REVIEW

**Review by wipfli — APPROVED** [review]
Looks great

**Comment by wipfli** [comment]
Maybe sort alphabetically by language that the user sees in the dropdown

**Comment by wipfli** [comment]
https://github.com/protomaps/basemaps/blob/8ec42aa5009bf6589a6bd9ae571f2d02aa28921d/app/src/MapViewComponent.tsx#L398C3-L398C80 like here

**Comment by bdon** [comment]
Fixed in https://github.com/protomaps/docs/pull/82

**Pull request merged**
